language: android

sudo: required

services:
  - docker

before_install:
    # Prepare the environment
    - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then openssl aes-256-cbc -K $encrypted_e2d0f76750b6_key -iv $encrypted_e2d0f76750b6_iv -in maven.keystore.gpg.enc -out maven.keystore.gpg -d; fi'
    - echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"
    - echo "TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}"
    - echo "TRAVIS_TAG=${TRAVIS_TAG}"
    - echo "TRAVIS_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}"
    - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo -e "android.signingConfigs.release.keyAlias=${signing_keyId}" >> "gradle.properties"; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo -e "android.signingConfigs.release.storePassword=${signing_password}" >> "gradle.properties"; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo -e "android.signingConfigs.release.keyPassword=${signing_password}" >> "gradle.properties"; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo -e "android.signingConfigs.release.storeFile=../maven.keystore.gpg" >> "gradle.properties"; fi'
    - echo -e "travisBuildNumber=${TRAVIS_BUILD_NUMBER}" >> "gradle.properties"
    - echo -e "travisBranch=${TRAVIS_BRANCH}" >> "gradle.properties"

    # Define the gradle tasks to be executed
    - gradleTasks="clean check"
    - 'if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then gradleTasks="$gradleTasks :btle-scanner-compat:publish"; fi'
    - echo $gradleTasks

    # Prepare the wrapper
    - chmod +x gradlew

    # Start docker image
    - docker run -d --name="android-build-image" -v "${PWD}:/target" -w "/target" -t toxicbakery/alpine-glibc-android:release-1.0.0 /bin/sh

script:
    # Execute
    - docker exec android-build-image /bin/sh -c "./gradlew $gradleTasks -Pprofile=sources,javadoc --continue --stacktrace"

notifications:
    email:
        - toxicbakery@gmail.com